packages/arco-markdown-loader/__test__/demo/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/i18n/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/usage/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/src/compiler/demo.ts
Use `React.memo` to avoid force refresh.
=> enhance: arco-markdown-loader use memo to avoid force refresh

packages/arco-scripts/package.json, packages/arco-scripts/src/config/style.config.ts, packages/arco-scripts/src/config/webpack/site.ts, yarn.lock
=> webpack site support autoprefixer

packages/arco-cli-block/src/main.ts
copy command invalid if target path does not exist in win10
```js
if(!isTargetPathExists){
await mkdirp(target);
}
```
=> fix: copy command invalid if target path does not exist

yarn.lock
=> fix: fix the error when bootstrap #17

packages/arco-cli-init/src/init.ts, packages/arco-cli-init/src/locale/en-US.ts, packages/arco-cli-init/src/locale/zh-CN.ts
| `arco init` 支持创建 `simple` 版本的 `arco-react-pro` | `arco init` supports creating a `simple` version of `arco-react-pro` | -------------- |
=> feat: cli support react-pro simple template

packages/arco-cli-init/src/init.ts, packages/arco-cli-init/src/locale/en-US.ts, packages/arco-cli-init/src/locale/zh-CN.ts
=> feat: support vue-pro simple template

isolate/arco-doc-site-components/components/CellCode/index.tsx, isolate/arco-doc-site-components/components/CellDescription/index.tsx, isolate/arco-doc-site-components/package.json, isolate/arco-doc-site-components/yarn.lock, packages/arco-markdown-loader/src/index.ts
- Add `aria-label` to document action button
=> enhance: add markdown-loader-aria

isolate/arco-doc-site-components/components/CellCode/index.tsx, isolate/arco-doc-site-components/components/CellDescription/index.tsx, isolate/arco-doc-site-components/components/CodeBlockWrapper/style/index.less
| support ts demo | 支持 ts demo | -------------- |
=> feat: support ts demo

isolate/arco-doc-site-components/components/CodeBlockWrapper/style/index.less, packages/arco-markdown-loader/src/compiler/demo.ts
Support Button focus style, improve accessibility.
=> style: Accessibility improvement

isolate/arco-doc-site-components/components/CellCode/index.tsx, isolate/arco-doc-site-components/package.json, packages/arco-markdown-loader/__test__/demo/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/demo/demo/basic.md, packages/arco-markdown-loader/__test__/demo/demo/size.md, packages/arco-markdown-loader/__test__/highlight/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/highlight/demo.md, packages/arco-markdown-loader/__test__/i18n/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/i18n/demo/basic.md, packages/arco-markdown-loader/__test__/i18n/demo/size.md, packages/arco-markdown-loader/__test__/usage/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/package.json, packages/arco-markdown-loader/src/compiler/demo.ts
更改 demo 解析方式以及相应的 sandbox/codepen 生成。
在 demo 中移除 ReactDOM 以及 CONTAINER，这样能更好地支持 demo中的 typescript 校验
* demo 变更:  js代码块由
```js
import { Button } from '@arco-design/web-react';
ReactDOM.render(<Button />, CONTAINER);
```
变更为
```js
import { Button } from '@arco-design/web-react';
const App = () => {
return <Button type="primary"> Primary </Button>;
};
export default App;
```
* Codesandbox 变更
1. 分为 demo.js (包含demo主逻辑) 和 index.js (包含ReactDOM.render)
2. 自动跳转到对应的 demo.js
* Codepen 变更
1. 将 demo 中的 export 替换为 ReactDOM.render
=> feat: 更改 demo 解析方式以及相应的 sandbox/codepen 生成

packages/arco-markdown-loader/__test__/demo/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/i18n/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/__test__/usage/__snapshots__/index.test.js.snap, packages/arco-markdown-loader/src/index.ts
当有 demos 时，需要往 ast 里塞入 commonImports
=> fix: append common imports when demos ast are present

packages/arco-scripts/src/config/jest/mdTransform.ts
=> feat: add tsx support for demo

packages/arco-scripts/src/config/jest/mdTransform.ts
在传递给 enzyme 前， 将 tsx 代码解析为 js 代码
=> fix: transform ts code before passed to enzyme

packages/arco-markdown-loader/src/getMeta.ts
Fix the problem: 'No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.'
Add parser
=> fix: add parser config to remove warnings

packages/arco-markdown-loader/src/getMeta.ts
close: https://github.com/arco-design/arco-design/issues/1489
=> fix: [arco-markdown-loader] support windows CRLF

README.md, package.json
The script enter dev mode in readme is not work.
Add a new script: dev in root package, exec `lerna run dev` with `--parallel`.
=> fix: add dev script to enter dev mode in root, and change readme.

fixtures/workspace/jest.config.js, packages/aspect/src/workspace/exceptions/index.ts, packages/aspect/src/workspace/exceptions/noIdMatchPatternError.ts, packages/aspect/src/workspace/workspace.ts, packages/core/src/cli/cliParser.ts, packages/service/src/tester/test.cmd.tsx
在build和test命令中，新增了支持指定组件和组件路径通配符功能
```bash
arco build 'components/**'
```
=> feat: 新增build匹配查找组件功能

packages/aspect/src/jest/jest.tester.ts
test 命令指定组件名称时，无法覆盖__test__目录下的其他文件，输出的测试报告包含了所有组件
=> feat:优化test指定组件时报告输出

packages/arco/src/app.ts, packages/legacy/src/analytics/analytics.ts, packages/legacy/src/bootstrap.ts, packages/legacy/src/cli/registerCommands.ts, packages/legacy/src/constants.ts, packages/legacy/src/utils/buildCommandMessage.ts, packages/legacy/src/utils/cliVersion.ts, packages/legacy/src/utils/index.ts, tsconfig.json
=> fix: cli version

isolate/arco-doc-site-components/components/CellCode/index.tsx, isolate/arco-doc-site-components/components/CellCode/juejin.svg, isolate/arco-doc-site-components/package.json
=> feat: support juejie playground
